apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    name: mongo-pod
    app: demo-voting-app
    tier: back-end
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
        - containerPort: 27017