apiVersion: v1
kind: Pod
metadata:
  name: result-pod
  labels:
    name: result-pod
    app: demo-voting-app
    tier: front-end
spec:
  containers:
    - name: result-app
      image: result-app:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 9002
      env:
        - name: MONGO_URL
          value: mongodb://mongo:27017/voting