apiVersion: v1
kind: Pod
metadata:
  name: voting-pod
  labels:
    name: voting-pod
    app: demo-voting-app
    tier: front-end
spec:
  containers:
    - name: voting-app
      image: voting-app:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 9001
      env:
        - name: REDIS_URL
          value: redis://redis:6379