apiVersion: v1
kind: Service
metadata:
  name: result-app
  labels:
    name: result-app-service
    app: demo-voting-app
spec:
  type: NodePort
  selector:
    name: result-pod
    app: demo-voting-app
    tier: front-end
  ports:
    - port: 9002
      targetPort: 9002
      nodePort: 30002