apiVersion: v1
kind: Service
metadata:
  name: voting-app
  labels:
    name: result-app-service
    app: demo-voting-app
spec:
  type: NodePort
  selector:
    name: voting-pod
    app: demo-voting-app
    tier: front-end
  ports:
    - port: 9001
      targetPort: 9001
      nodePort: 30001